<a href="https://colab.research.google.com/github/mrri-18/swu_2/blob/main/scipy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
from scipy import sparse

eye=np.eye(4)
print("NumPy array: \n",eye)


NumPy array: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
sparse_matrix=sparse.csr_matrix(eye) #sparse=희소 행렬 기능 제공
print("\n CSR 행렬:\n", sparse_matrix)


 CSR 행렬:
   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [10]:
data=np.ones(4) #희소 행렬을 직접 만드는 것 onse함수: 1로 가득찬 배열 생성
row_indices=np.arange(4) #[0,1,2,3]
col_indices=np.arange(4) #[0,1,2,3]
eye_coo=sparse.coo_matrix((data, (row_indices, col_indices))) #이 좌표에만 값 1이 저장됨
print("COO 표현:\n", eye_coo)

COO 표현:
   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
